# Generated by Django 3.1.2 on 2020-11-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('image_url', models.ImageField(upload_to='conflicts/', verbose_name='Изображение')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Противопоказание',
                'verbose_name_plural': 'Противопоказания',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='diseases/', verbose_name='Изображение')),
                ('symptoms', models.TextField(max_length=3000, verbose_name='Симптомы')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Заболевание',
                'verbose_name_plural': 'Заболевания',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип')),
                ('desc', models.TextField(max_length=2000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='pills/', verbose_name='Изображение')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('conflicts', models.ManyToManyField(related_name='pill_conflict', to='diseases.Conflict', verbose_name='Противопоказания')),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectivity', models.FloatField(default=0, help_text='0-100, указывать в процентах(%)', verbose_name='Еффективность')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.disease', verbose_name='Заболевание')),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.pill', verbose_name='Лекарство')),
            ],
            options={
                'verbose_name': 'Эффективность',
                'verbose_name_plural': 'Эффективность',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='types',
            field=models.ManyToManyField(related_name='disease_type', to='diseases.Type', verbose_name='Тип'),
        ),
    ]
