# Generated by Django 3.1.3 on 2020-11-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_auto_20201115_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
